### ISSUE TITLE
建议升级javassist到3.23.1-GA，以便支持java11

### ISSUE THREAD

**Issue by hypnos-popeye** [jetlinks/jetlinks-community#104]
在java11下编译官方驱动，test阶段会报如下错误：
[Test worker] ERROR o.h.web.bean.FastBeanCopier - 创建bean copy 代理对象失败:
public void copy(Object s, Object t, java.util.Set ignore, org.hswebframework.web.bean.Converter converter){
try{
	org.jetlinks.core.message.ChildDeviceMessage $$__source=(org.jetlinks.core.message.ChildDeviceMessage)s;
	java.util.Map $$__target=(java.util.Map)t;
	if(!ignore.contains("headers")){
	if($$__source.getHeaders()!=null){
java.lang.Object headers=(java.lang.Object)(converter.convert((Object)($$__source.getHeaders()),java.lang.Object.class,org.hswebframework.web.bean.FastBeanCopier.EMPTY_CLASS_ARRAY));
	if(headers!=null){
	$$__target.put("headers",headers);
	}
	}
}
if(!ignore.contains("code")){
	if($$__source.getCode()!=null){
java.lang.Object code=(java.lang.Object)(converter.convert((Object)($$__source.getCode()),java.lang.Object.class,org.hswebframework.web.bean.FastBeanCopier.EMPTY_CLASS_ARRAY));
	if(code!=null){
	$$__target.put("code",code);
	}
	}
}
if(!ignore.contains("messageId")){
	if($$__source.getMessageId()!=null){
java.lang.Object messageId=(java.lang.Object)(converter.convert((Object)($$__source.getMessageId()),java.lang.Object.class,org.hswebframework.web.bean.FastBeanCopier.EMPTY_CLASS_ARRAY));
	if(messageId!=null){
	$$__target.put("messageId",messageId);
	}
	}
}
if(!ignore.contains("deviceId")){
	if($$__source.getDeviceId()!=null){
java.lang.Object deviceId=(java.lang.Object)(converter.convert((Object)($$__source.getDeviceId()),java.lang.Object.class,org.hswebframework.web.bean.FastBeanCopier.EMPTY_CLASS_ARRAY));
	if(deviceId!=null){
	$$__target.put("deviceId",deviceId);
	}
	}
}
if(!ignore.contains("timestamp")){
	java.lang.Object timestamp=(java.lang.Object)(converter.convert((Object)(Long.valueOf($$__source.getTimestamp())),java.lang.Object.class,org.hswebframework.web.bean.FastBeanCopier.EMPTY_CLASS_ARRAY));
	if(timestamp!=null){
	$$__target.put("timestamp",timestamp);
	}
}
if(!ignore.contains("childDeviceId")){
	if($$__source.getChildDeviceId()!=null){
java.lang.Object childDeviceId=(java.lang.Object)(converter.convert((Object)($$__source.getChildDeviceId()),java.lang.Object.class,org.hswebframework.web.bean.FastBeanCopier.EMPTY_CLASS_ARRAY));
	if(childDeviceId!=null){
	$$__target.put("childDeviceId",childDeviceId);
	}
	}
}
if(!ignore.contains("childDeviceMessage")){
	if($$__source.getChildDeviceMessage()!=null){
java.lang.Object childDeviceMessage=(java.lang.Object)(converter.convert((Object)($$__source.getChildDeviceMessage()),java.lang.Object.class,org.hswebframework.web.bean.FastBeanCopier.EMPTY_CLASS_ARRAY));
	if(childDeviceMessage!=null){
	$$__target.put("childDeviceMessage",childDeviceMessage);
	}
	}
}
}catch(Exception e){
	throw new RuntimeException(e.getMessage(),e);
}

} 
java.lang.NullPointerException: null
	at javassist.util.proxy.SecurityActions.setAccessible(SecurityActions.java:103)
	at javassist.util.proxy.DefineClassHelper.toClass3(DefineClassHelper.java:151)
	at javassist.util.proxy.DefineClassHelper.toClass2(DefineClassHelper.java:134)
	at javassist.util.proxy.DefineClassHelper.toClass(DefineClassHelper.java:95)
	at javassist.ClassPool.toClass(ClassPool.java:1143)
	at javassist.CtClass.toClass(CtClass.java:1316)
	at org.hswebframework.web.proxy.Proxy.getTargetClass(Proxy.java:156)
	at org.hswebframework.web.proxy.Proxy.newInstance(Proxy.java:150)
	at org.hswebframework.web.bean.FastBeanCopier.createCopier(FastBeanCopier.java:171)
	at org.hswebframework.web.bean.FastBeanCopier.lambda$getCopier$0(FastBeanCopier.java:138)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at org.hswebframework.web.bean.FastBeanCopier.getCopier(FastBeanCopier.java:138)
	at org.hswebframework.web.bean.FastBeanCopier.copy(FastBeanCopier.java:114)
	at org.hswebframework.web.bean.FastBeanCopier.copy(FastBeanCopier.java:100)
	at org.hswebframework.web.bean.FastBeanCopier.copy(FastBeanCopier.java:87)
	at org.jetlinks.core.message.CommonDeviceMessage.toJson(CommonDeviceMessage.java:96)
	at org.jetlinks.core.message.ChildDeviceMessage.toJson(ChildDeviceMessage.java:51)
	at org.jetlinks.core.message.CommonDeviceMessage.toString(CommonDeviceMessage.java:108)
	at org.jetlinks.protocol.official.JetLinksMqttDeviceMessageCodecTest.createMessageContext(JetLinksMqttDeviceMessageCodecTest.java:399)
	at org.jetlinks.protocol.official.JetLinksMqttDeviceMessageCodecTest.testChildWriteProperty(JetLinksMqttDeviceMessageCodecTest.java:155)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:686)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:212)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:208)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:137)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:71)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:102)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:82)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:78)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:132)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:829)

经过分析发现`org.hswebframework.web.proxy.Proxy`用了javassist-2.22，`DefineClassHelper`类中在大于java9时未初始化`defineClass1`。javassist-2.23.1-GA修复了该问题，经本人测试可以正常编译通过。

**Comment by zhou-hao** [comment]
hsweb `4.0.13-SNAPSHOT`中升级
