### ISSUE TITLE
直接内存溢出

### ISSUE THREAD

**Issue by chanlk** [jetlinks/jetlinks-community#128]
运行久了之后会报错，下面是日志，设备很少。

还需要其他参数协助吗？

`[2021-12-23 07:39:06.509] [ERROR] [reactor-http-epoll-1] [ip-10-0-10-40] [default]
                [ip-10-0-10-40] [reactor.netty.tcp.TcpServer.error][319] [[id: 0x9585926a, L:/10.0.10.40:8844 - R:/10.0.10.95:3192] onUncaughtException(SimpleConnection{channel=[id: 0x9585926a, L:/10.0.10.40:8844 - R:/10.0.10.95:3192]})]
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 2130706439, max: 2147483648)
        at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:754)
        at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:709)
        at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:755)
        at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:731)
        at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:247)
        at io.netty.buffer.PoolArena.allocate(PoolArena.java:215)
        at io.netty.buffer.PoolArena.allocate(PoolArena.java:147)
        at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:356)
        at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)
        at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:178)
        at io.netty.channel.unix.PreferredDirectByteBufAllocator.ioBuffer(PreferredDirectByteBufAllocator.java:53)
        at io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:114)
        at io.netty.channel.epoll.EpollRecvByteAllocatorHandle.allocate(EpollRecvByteAllocatorHandle.java:75)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:777)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)`

**Comment by zhou-hao** [comment]
这是做什么的时候。 什么版本。还有没有其他错误信息。

**Comment by chanlk** [comment]
1.10版本。 不确定是做什么的时候，因为那个错误日志一直刷，全都是重复的。看到有错误日志中间夹杂着下面的日志，不知道是不是这个导致的。

`[2021-12-23 07:15:45.056] [DEBUG] [vert.x-eventloop-thread-0] [ip-10-0-10-40] [default]
                [ip-10-0-10-40] [org.jetlinks.pro.network.mqtt.server.vertx.VertxMqttConnection.acknowledge][430] [PUBACK QoS1 mqtt[HMJQ24DBLS28LK8CZZZZKY8M] message[8]]
[2021-12-23 07:15:45.057] [INFO ] [vert.x-eventloop-thread-0] [ip-10-0-10-40] [default]
                [ip-10-0-10-40] [org.jetlinks.pro.network.monitor.mqtt-server.bytesRead][39] [receive number of bytes :141]
[2021-12-23 07:15:45.207] [DEBUG] [vert.x-eventloop-thread-0] [ip-10-0-10-40] [default]
                [ip-10-0-10-40] [org.jetlinks.pro.network.mqtt.server.vertx.VertxMqttConnection.acknowledge][430] [PUBACK QoS1 mqtt[HMJQ24DBLS28LK8CZZZZKY8M] message[9]]
[2021-12-23 07:15:45.208] [INFO ] [vert.x-eventloop-thread-0] [ip-10-0-10-40] [default]
                [ip-10-0-10-40] [org.jetlinks.pro.network.monitor.mqtt-server.bytesRead][39] [receive number of bytes :136]
[2021-12-23 07:15:45.358] [ERROR] [reactor-http-epoll-1] [ip-10-0-10-40] [default]
`

**Comment by zhou-hao** [comment]
社区版？有没有自定义接口、或者直接操作ServerExchange



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: chanlk ***@***.***&gt;
发送时间: 2021年12月24日 17:19
收件人: jetlinks/jetlinks-community ***@***.***&gt;
抄送: 老周 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [jetlinks/jetlinks-community] 直接内存溢出 (Issue #128)





 
1.10版本。 不确定是做什么的时候，因为那个错误日志一直刷，全都是重复的。看到有错误日志中间夹杂着下面的日志，不知道是不是这个导致的。
 
[2021-12-23 07:15:45.056] [DEBUG] [vert.x-eventloop-thread-0] [ip-10-0-10-40] [default] [ip-10-0-10-40] [org.jetlinks.pro.network.mqtt.server.vertx.VertxMqttConnection.acknowledge][430] [PUBACK QoS1 mqtt[HMJQ24DBLS28LK8CZZZZKY8M] message[8]] [2021-12-23 07:15:45.057] [INFO ] [vert.x-eventloop-thread-0] [ip-10-0-10-40] [default] [ip-10-0-10-40] [org.jetlinks.pro.network.monitor.mqtt-server.bytesRead][39] [receive number of bytes :141] [2021-12-23 07:15:45.207] [DEBUG] [vert.x-eventloop-thread-0] [ip-10-0-10-40] [default] [ip-10-0-10-40] [org.jetlinks.pro.network.mqtt.server.vertx.VertxMqttConnection.acknowledge][430] [PUBACK QoS1 mqtt[HMJQ24DBLS28LK8CZZZZKY8M] message[9]] [2021-12-23 07:15:45.208] [INFO ] [vert.x-eventloop-thread-0] [ip-10-0-10-40] [default] [ip-10-0-10-40] [org.jetlinks.pro.network.monitor.mqtt-server.bytesRead][39] [receive number of bytes :136] [2021-12-23 07:15:45.358] [ERROR] [reactor-http-epoll-1] [ip-10-0-10-40] [default]

**Comment by chanlk** [comment]
社区的1.0版本。看不到什么操作，全是这样的日志，重复的。有自定义接口，看日志的第一行是调用了这边的8844接口

**Comment by zhou-hao** [comment]
看看请求日志 最多的请求是啥



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: chanlk ***@***.***&gt;
发送时间: 2021年12月24日 17:50
收件人: jetlinks/jetlinks-community ***@***.***&gt;
抄送: 老周 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [jetlinks/jetlinks-community] 直接内存溢出 (Issue #128)





 
社区的1.0版本。看不到什么操作，全是这样的日志，重复的。有自定义接口，看日志的第一行是调用了这边的8844接口

**Comment by zhou-hao** [comment]
有啥最新进展？
