### ISSUE TITLE
从源码部署时老停在这个错误不知道如何解决

### ISSUE THREAD

**Issue by xiaohelong** [jetlinks/jetlinks-community#156]
022-04-14 21:04:56.431 DEBUG 13984 --- \[actor-tcp-nio-1\] o.h.e.r.e.r.r.R2dbcReactiveSqlExecutor   : ==>     Native: select A.SCHEMANAME::varchar, A.TABLENAME::varchar, A.INDEXNAME::varchar, IA.ATTNAME::varchar, IA.ATTNUM::int2, A.TABLESPACE::varchar, B.AMNAME::varchar, C.INDNATTS::varchar, C.INDISUNIQUE::boolean, C.INDISPRIMARY::boolean, C.INDISCLUSTERED::boolean, D.DESCRIPTION::varchar from PG\_AM B left join PG\_CLASS F on B.OID = F.RELAM left join PG\_STAT\_ALL\_INDEXES E on F.OID = E.INDEXRELID left join PG\_INDEX C on E.INDEXRELID = C.INDEXRELID left outer join PG\_DESCRIPTION D on C.INDEXRELID = D.OBJOID left join pg\_attribute IA on IA.attrelid = F.oid , PG\_INDEXES A where A.SCHEMANAME = E.SCHEMANAME and A.TABLENAME = E.RELNAME and A.INDEXNAME = E.INDEXRELNAME and E.SCHEMANAME = 'public'  
2022-04-14 21:04:57.058 ERROR 13984 --- \[           main\] o.h.web.bean.FastBeanCopier              : 创建bean copy 代理对象失败:  
public void copy(Object s, Object t, java.util.Set ignore, org.hswebframework.web.bean.Converter converter){  
try{  
org.jetlinks.core.cluster.ServerNode $$\_\_source=(org.jetlinks.core.cluster.ServerNode)s;  
org.jetlinks.core.cluster.ServerNode $$\_\_target=(org.jetlinks.core.cluster.ServerNode)t;  
if(!ignore.contains("id")){  
if($$\_\_source.getId()!=null){  
java.lang.String id=(java.lang.String)$$\_\_source.getId();  
if(id!=null){  
$$\_\_target.setId(id);  
}  
}  
}  
if(!ignore.contains("name")){  
if($$\_\_source.getName()!=null){  
java.lang.String name=(java.lang.String)$$\_\_source.getName();  
if(name!=null){  
$$\_\_target.setName(name);  
}  
}  
}  
if(!ignore.contains("host")){  
if($$\_\_source.getHost()!=null){  
java.lang.String host=(java.lang.String)$$\_\_source.getHost();  
if(host!=null){  
$$\_\_target.setHost(host);  
}  
}  
}  
if(!ignore.contains("tags")){  
if($$\_\_source.getTags()!=null){  
java.util.Map tags=(java.util.Map)converter.convert((Object)($$\_\_source.getTags()),java.util.Map.class,new Class\[\]{java.lang.String.class,java.lang.Object.class});  
if(tags!=null){  
$$\_\_target.setTags(tags);  
}  
}  
}  
if(!ignore.contains("leader")){  
boolean leader=(boolean)$$\_\_source.isLeader();  
$$\_\_target.setLeader(leader);  
}  
if(!ignore.contains("uptime")){  
long uptime=(long)$$\_\_source.getUptime();  
$$\_\_target.setUptime(uptime);  
}  
if(!ignore.contains("lastKeepAlive")){  
long lastKeepAlive=(long)$$\_\_source.getLastKeepAlive();  
$$\_\_target.setLastKeepAlive(lastKeepAlive);  
}  
}catch(Exception e){  
throw new RuntimeException(e.getMessage(),e);  
}

}

java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte\[\],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @797db435  
at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)  
at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)  
at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)  
at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)  
at javassist.ClassPool.toClass2(ClassPool.java:1181)  
at javassist.ClassPool.toClass(ClassPool.java:1164)  
at javassist.CtClass.toClass(CtClass.java:1316)  
at org.hswebframework.web.proxy.Proxy.getTargetClass(Proxy.java:156)  
at org.hswebframework.web.proxy.Proxy.newInstance(Proxy.java:150)  
at org.hswebframework.web.bean.FastBeanCopier.createCopier(FastBeanCopier.java:181)  
at org.hswebframework.web.bean.FastBeanCopier.lambda$getCopier$0(FastBeanCopier.java:148)  
at java.base/java.util.concurrent.ConcurrentMap.computeIfAbsent(ConcurrentMap.java:330)  
at org.hswebframework.web.bean.FastBeanCopier.getCopier(FastBeanCopier.java:148)  
at org.hswebframework.web.bean.FastBeanCopier.copy(FastBeanCopier.java:124)  
at org.hswebframework.web.bean.FastBeanCopier.copy(FastBeanCopier.java:110)  
at org.hswebframework.web.bean.FastBeanCopier.copy(FastBeanCopier.java:97)  
at org.jetlinks.core.cluster.ServerNode.copy(ServerNode.java:47)  
at org.jetlinks.supports.cluster.redis.RedisHaManager.\<init>(RedisHaManager.java:56)  
at org.jetlinks.supports.cluster.redis.RedisClusterManager.\<init>(RedisClusterManager.java:47)  
at org.jetlinks.supports.cluster.redis.RedisClusterManager.\<init>(RedisClusterManager.java:65)  
at org.jetlinks.community.standalone.configuration.JetLinksConfiguration.clusterManager(JetLinksConfiguration.java:101)  
at org.jetlinks.community.standalone.configuration.JetLinksConfiguration$$EnhancerBySpringCGLIB$$4f29eaad.CGLIB$clusterManager$14(\<generated>)  
at org.jetlinks.community.standalone.configuration.JetLinksConfiguration$$EnhancerBySpringCGLIB$$4f29eaad$$FastClassBySpringCGLIB$$e8be9433.invoke(\<generated>)  
at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)  
at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)  
at org.jetlinks.community.standalone.configuration.JetLinksConfiguration$$EnhancerBySpringCGLIB$$4f29eaad.clusterManager(\<generated>)  
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)  
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  
at java.base/java.lang.reflect.Method.invoke(Method.java:568)  
at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)  
at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:652)  
at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:637)  
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1341)  
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1181)  
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:556)  
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)  
at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)  
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)  
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)  
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)  
at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)  
at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1307)  
at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1227)  
at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:886)  
at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:790)  
at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:540)  
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1341)  
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1181)  
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:556)  
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)  
at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)  
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)  
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)  
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)  
at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)  
at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1307)  
at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1227)  
at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:886)  
at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:790)  
at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:540)  
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1341)  
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1181)  
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:556)  
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)  
at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)  
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)  
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)  
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:207)  
at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:241)  
at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:723)  
at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:536)  
at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:62)  
at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:755)  
at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)  
at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:402)  
at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)  
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1247)  
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1236)  
at org.jetlinks.community.standalone.JetLinksApplication.main(JetLinksApplication.java:33)

2022-04-14 21:04:57.061  WARN 13984 --- \[           main\] onfigReactiveWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'interceptorRegister' defined in class path resource \[org/jetlinks/community/standalone/configuration/JetLinksConfiguration.class\]: Unsatisfied dependency expressed through method 'interceptorRegister' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'clusterDeviceRegistry' defined in class path resource \[org/jetlinks/community/standalone/configuration/JetLinksConfiguration.class\]: Unsatisfied dependency expressed through method 'clusterDeviceRegistry' parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'clusterManager' defined in class path resource \[org/jetlinks/community/standalone/configuration/JetLinksConfiguration.class\]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate \[org.jetlinks.supports.cluster.redis.RedisClusterManager\]: Factory method 'clusterManager' threw exception; nested exception is java.lang.UnsupportedOperationException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte\[\],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @797db435  
2022-04-14 21:04:57.127 ERROR 13984 --- \[           main\] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'interceptorRegister' defined in class path resource \[org/jetlinks/community/standalone/configuration/JetLinksConfiguration.class\]: Unsatisfied dependency expressed through method 'interceptorRegister' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'clusterDeviceRegistry' defined in class path resource \[org/jetlinks/community/standalone/configuration/JetLinksConfiguration.class\]: Unsatisfied dependency expressed through method 'clusterDeviceRegistry' parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'clusterManager' defined in class path resource \[org/jetlinks/community/standalone/configuration/JetLinksConfiguration.class\]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate \[org.jetlinks.supports.cluster.redis.RedisClusterManager\]: Factory method 'clusterManager' threw exception; nested exception is java.lang.UnsupportedOperationException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte\[\],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @797db435  
at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:799)  
at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:540)  
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1341)  
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1181)  
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:556)  
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)  
at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)  
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)  
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)  
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:207)  
at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:241)  
at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:723)  
at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:536)  
at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:62)  
at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:755)  
at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)  
at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:402)  
at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)  
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1247)  
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1236)  
at org.jetlinks.community.standalone.JetLinksApplication.main(JetLinksApplication.java:33)  
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'clusterDeviceRegistry' defined in class path resource \[org/jetlinks/community/standalone/configuration/JetLinksConfiguration.class\]: Unsatisfied dependency expressed through method 'clusterDeviceRegistry' parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'clusterManager' defined in class path resource \[org/jetlinks/community/standalone/configuration/JetLinksConfiguration.class\]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate \[org.jetlinks.supports.cluster.redis.RedisClusterManager\]: Factory method 'clusterManager' threw exception; nested exception is java.lang.UnsupportedOperationException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte\[\],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @797db435  
at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:799)  
at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:540)  
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1341)  
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1181)  
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:556)  
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)  
at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)  
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)  
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)  
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)  
at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)  
at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1307)  
at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1227)  
at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:886)  
at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:790)  
... 20 common frames omitted  
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'clusterManager' defined in class path resource \[org/jetlinks/community/standalone/configuration/JetLinksConfiguration.class\]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate \[org.jetlinks.supports.cluster.redis.RedisClusterManager\]: Factory method 'clusterManager' threw exception; nested exception is java.lang.UnsupportedOperationException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte\[\],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @797db435  
at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:657)  
at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:637)  
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1341)  
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1181)  
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:556)  
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)  
at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)  
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)  
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)  
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)  
at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)  
at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1307)  
at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1227)  
at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:886)  
at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:790)  
... 34 common frames omitted  
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate \[org.jetlinks.supports.cluster.redis.RedisClusterManager\]: Factory method 'clusterManager' threw exception; nested exception is java.lang.UnsupportedOperationException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte\[\],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @797db435  
at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)  
at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:652)  
... 48 common frames omitted  
Caused by: java.lang.UnsupportedOperationException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte\[\],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @797db435  
at org.hswebframework.web.bean.FastBeanCopier.createCopier(FastBeanCopier.java:184)  
at org.hswebframework.web.bean.FastBeanCopier.lambda$getCopier$0(FastBeanCopier.java:148)  
at java.base/java.util.concurrent.ConcurrentMap.computeIfAbsent(ConcurrentMap.java:330)  
at org.hswebframework.web.bean.FastBeanCopier.getCopier(FastBeanCopier.java:148)  
at org.hswebframework.web.bean.FastBeanCopier.copy(FastBeanCopier.java:124)  
at org.hswebframework.web.bean.FastBeanCopier.copy(FastBeanCopier.java:110)  
at org.hswebframework.web.bean.FastBeanCopier.copy(FastBeanCopier.java:97)  
at org.jetlinks.core.cluster.ServerNode.copy(ServerNode.java:47)  
at org.jetlinks.supports.cluster.redis.RedisHaManager.\<init>(RedisHaManager.java:56)  
at org.jetlinks.supports.cluster.redis.RedisClusterManager.\<init>(RedisClusterManager.java:47)  
at org.jetlinks.supports.cluster.redis.RedisClusterManager.\<init>(RedisClusterManager.java:65)  
at org.jetlinks.community.standalone.configuration.JetLinksConfiguration.clusterManager(JetLinksConfiguration.java:101)  
at org.jetlinks.community.standalone.configuration.JetLinksConfiguration$$EnhancerBySpringCGLIB$$4f29eaad.CGLIB$clusterManager$14(\<generated>)  
at org.jetlinks.community.standalone.configuration.JetLinksConfiguration$$EnhancerBySpringCGLIB$$4f29eaad$$FastClassBySpringCGLIB$$e8be9433.invoke(\<generated>)  
at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)  
at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)  
at org.jetlinks.community.standalone.configuration.JetLinksConfiguration$$EnhancerBySpringCGLIB$$4f29eaad.clusterManager(\<generated>)  
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)  
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  
at java.base/java.lang.reflect.Method.invoke(Method.java:568)  
at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)  
... 49 common frames omitted  
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte\[\],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @797db435  
at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)  
at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)  
at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)  
at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)  
at javassist.ClassPool.toClass2(ClassPool.java:1181)  
at javassist.ClassPool.toClass(ClassPool.java:1164)  
at javassist.CtClass.toClass(CtClass.java:1316)  
at org.hswebframework.web.proxy.Proxy.getTargetClass(Proxy.java:156)  
at org.hswebframework.web.proxy.Proxy.newInstance(Proxy.java:150)  
at org.hswebframework.web.bean.FastBeanCopier.createCopier(FastBeanCopier.java:181)  
... 70 common frames omitted

Disconnected from the target VM, address: '127.0.0.1:58261', transport: 'socket'

Process finished with exit code 1

**Comment by xiaohelong** [comment]
是的，感谢回答。我搞了好几天就卡在这里。以前装了一个1。8，也没用，后面才发现是51
