### ISSUE TITLE
Docker run all 启动后创建ES索引错误

### ISSUE THREAD

**Issue by wujun8** [jetlinks/jetlinks-community#165]
jetlinks-standalone:1.13.0-SNAPSHOT
elasticsearch:7.6.2 如果是版本 6 系统前端就有报错

访问日志，系统日志，没有报错了，但都查询不到任何数据

```
jetlinks-ce      | 2022-05-27 15:11:52.241 ERROR 6 --- [or-http-epoll-1] o.j.c.t.m.TimeSeriesMeterRegistry        : register metric [jetlinks-metrics] metadata error
jetlinks-ce      |
jetlinks-ce      | org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=illegal_argument_exception, reason=mapper [server] of different type, current_type [text], merged_type [keyword]], Elasticsearch exception [type=illegal_argument_exception, reason=mapper [server] of different type, current_type [text], merged_type [keyword]]
jetlinks-ce      | 	at org.jetlinks.community.elastic.search.service.reactive.DefaultReactiveElasticsearchClient.contentOrError(DefaultReactiveElasticsearchClient.java:964)
jetlinks-ce      | 	at org.jetlinks.community.elastic.search.service.reactive.DefaultReactiveElasticsearchClient.lambda$handleClientError$36(DefaultReactiveElasticsearchClient.java:937)
jetlinks-ce      | 	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:118)
jetlinks-ce      | 	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)
jetlinks-ce      | 	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:385)
jetlinks-ce      | 	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)
jetlinks-ce      | 	at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onNext(FluxContextStart.java:96)
jetlinks-ce      | 	at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onNext(FluxMapFuseable.java:287)
jetlinks-ce      | 	at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.onNext(FluxFilterFuseable.java:330)
jetlinks-ce      | 	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1812)
jetlinks-ce      | 	at reactor.core.publisher.MonoCollect$CollectSubscriber.onComplete(MonoCollect.java:152)
jetlinks-ce      | 	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136)
jetlinks-ce      | 	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:252)
jetlinks-ce      | 	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136)
jetlinks-ce      | 	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:383)
jetlinks-ce      | 	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:373)
jetlinks-ce      | 	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:429)
jetlinks-ce      | 	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:655)
jetlinks-ce      | 	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:96)
jetlinks-ce      | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
jetlinks-ce      | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
jetlinks-ce      | 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
jetlinks-ce      | 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
jetlinks-ce      | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
jetlinks-ce      | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
jetlinks-ce      | 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
jetlinks-ce      | 	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
jetlinks-ce      | 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
jetlinks-ce      | 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
jetlinks-ce      | 	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
jetlinks-ce      | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
jetlinks-ce      | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
jetlinks-ce      | 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
jetlinks-ce      | 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
jetlinks-ce      | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
jetlinks-ce      | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
jetlinks-ce      | 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
jetlinks-ce      | 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
jetlinks-ce      | 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
jetlinks-ce      | 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
jetlinks-ce      | 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
jetlinks-ce      | 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
jetlinks-ce      | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
jetlinks-ce      | 	at java.lang.Thread.run(Thread.java:748)
jetlinks-ce      | Caused by: org.elasticsearch.ElasticsearchException: Elasticsearch exception [type=illegal_argument_exception, reason=mapper [server] of different type, current_type [text], merged_type [keyword]]
jetlinks-ce      | 	at org.elasticsearch.ElasticsearchException.innerFromXContent(ElasticsearchException.java:485)
jetlinks-ce      | 	at org.elasticsearch.ElasticsearchException.failureFromXContent(ElasticsearchException.java:592)
jetlinks-ce      | 	at org.jetlinks.community.elastic.search.service.reactive.DefaultReactiveElasticsearchClient.getElasticsearchException(DefaultReactiveElasticsearchClient.java:989)
jetlinks-ce      | 	at org.jetlinks.community.elastic.search.service.reactive.DefaultReactiveElasticsearchClient.contentOrError(DefaultReactiveElasticsearchClient.java:955)
jetlinks-ce      | 	... 43 common frames omitted
jetlinks-ce      | 	Suppressed: org.elasticsearch.ElasticsearchException: Elasticsearch exception [type=illegal_argument_exception, reason=mapper [server] of different type, current_type [text], merged_type [keyword]]
jetlinks-ce      | 		at org.elasticsearch.ElasticsearchException.innerFromXContent(ElasticsearchException.java:485)
jetlinks-ce      | 		at org.elasticsearch.ElasticsearchException.fromXContent(ElasticsearchException.java:396)
jetlinks-ce      | 		at org.elasticsearch.ElasticsearchException.innerFromXContent(ElasticsearchException.java:458)
jetlinks-ce      | 		... 46 common frames omitted
jetlinks-ce      |
```

**Comment by zhou-hao** [comment]
这是因为 索引未成功创建 就产生了数据，导致索引错误。停止jetlinks，删除对应的索引。重启jetlinks。
