### ISSUE TITLE
Elasticsearch 异常本地运行项目

### ISSUE THREAD

**Issue by tlchun** [jetlinks/jetlinks-community#19]
2020-09-10 09:34:41.680  INFO 30688 --- [           main] o.j.c.standalone.JetLinksApplication     : Starting JetLinksApplication on tcl-OptiPlex-9020 with PID 30688 (/home/tcl/java_project/jetlinks-community/jetlinks-standalone/target/jetlinks-standalone.jar started by root in /home/tcl/java_project/jetlinks-community)
2020-09-10 09:34:41.685 DEBUG 30688 --- [           main] o.j.c.standalone.JetLinksApplication     : Running with Spring Boot v2.3.3.RELEASE, Spring v5.2.8.RELEASE
2020-09-10 09:34:41.685  INFO 30688 --- [           main] o.j.c.standalone.JetLinksApplication     : The following profiles are active: dev
2020-09-10 09:34:47.797 DEBUG 30688 --- [           main] o.j.supports.event.BrokerEventBus        : local subscriber [spring:DeviceMessageMeasurementProvider.incrementMessage],features:[local],topics: [/device/*/*/message/**]
2020-09-10 09:34:47.955 DEBUG 30688 --- [           main] o.j.supports.event.BrokerEventBus        : local subscriber [spring:RuleLogHandler.handleEvent],features:[local],topics: [/rule-engine/*/*/event/*]
2020-09-10 09:34:47.957 DEBUG 30688 --- [           main] o.j.supports.event.BrokerEventBus        : local subscriber [spring:RuleLogHandler.handleLog],features:[local],topics: [/rule-engine/*/*/logger/*]
2020-09-10 09:34:48.049 ERROR 30688 --- [or-http-epoll-1] o.j.c.t.m.TimeSeriesMeterRegistry        : register metric [device_metrics] metadata error

org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=exception, reason=ActionRequestValidationException[Validation Failed: 1: template is missing;]]
	at org.jetlinks.community.elastic.search.service.reactive.DefaultReactiveElasticsearchClient.contentOrError(DefaultReactiveElasticsearchClient.java:857)
	at org.jetlinks.community.elastic.search.service.reactive.DefaultReactiveElasticsearchClient.lambda$handleClientError$32(DefaultReactiveElasticsearchClient.java:834)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:118)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:385)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)
	at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onNext(FluxContextStart.java:96)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onNext(FluxMapFuseable.java:287)
	at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.onNext(FluxFilterFuseable.java:330)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)
	at reactor.core.publisher.MonoCollect$CollectSubscriber.onComplete(MonoCollect.java:152)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:252)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136)
	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:378)
	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:373)
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:429)
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:625)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:96)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.elasticsearch.ElasticsearchException: Elasticsearch exception [type=exception, reason=ActionRequestValidationException[Validation Failed: 1: template is missing;]]
	at org.elasticsearch.ElasticsearchException.failureFromXContent(ElasticsearchException.java:596)
	at org.jetlinks.community.elastic.search.service.reactive.DefaultReactiveElasticsearchClient.getElasticsearchException(DefaultReactiveElasticsearchClient.java:882)
	at org.jetlinks.community.elastic.search.service.reactive.DefaultReactiveElasticsearchClient.contentOrError(DefaultReactiveElasticsearchClient.java:852)
	... 43 common frames omitted

**Comment by zhou-hao** [comment]
更新到最新 还会报错不
