### ISSUE TITLE
JetLinks 自定义协议报错

### ISSUE THREAD

**Issue by marshalby2** [jetlinks/jetlinks-community#194]
# 问题描述
JetLinks 自定义协议测试时报错。
# 解决过程
我去hsweb仓库看到三个类似的issue，都无法解决
# 版本信息
jdk: 1.8
JetLinks: 1.20.0-SNAPSHOT
hsweb: 4.0.15-SNAPSHOT
# 错误信息
`2022-08-16 17:04:32.070 ERROR 4644 --- [ioEventLoop-4-1] o.h.web.bean.FastBeanCopier              : 创建bean copy 代理对象失败:
public void copy(Object s, Object t, java.util.Set ignore, org.hswebframework.web.bean.Converter converter){
try{
	com.hiscene.hilink.taixing.message.TXTriggerTrafficDataInRealTimeMessage $$__source=(com.hiscene.hilink.taixing.message.TXTriggerTrafficDataInRealTimeMessage)s;
	java.util.Map $$__target=(java.util.Map)t;
	if(!ignore.contains("code")){
	if($$__source.getCode()!=null){
java.lang.Object code=(java.lang.Object)(converter.convert((Object)($$__source.getCode()),java.lang.Object.class,org.hswebframework.web.bean.FastBeanCopier.EMPTY_CLASS_ARRAY));
	if(code!=null){
	$$__target.put("code",code);
	}
	}
}
if(!ignore.contains("deviceId")){
	if($$__source.getDeviceId()!=null){
java.lang.Object deviceId=(java.lang.Object)(converter.convert((Object)($$__source.getDeviceId()),java.lang.Object.class,org.hswebframework.web.bean.FastBeanCopier.EMPTY_CLASS_ARRAY));
	if(deviceId!=null){
	$$__target.put("deviceId",deviceId);
	}
	}
}
if(!ignore.contains("startTime")){
	if($$__source.getStartTime()!=null){
java.lang.Object startTime=(java.lang.Object)(converter.convert((Object)($$__source.getStartTime()),java.lang.Object.class,org.hswebframework.web.bean.FastBeanCopier.EMPTY_CLASS_ARRAY));
	if(startTime!=null){
	$$__target.put("startTime",startTime);
	}
	}
}
if(!ignore.contains("timestamp")){
	java.lang.Object timestamp=(java.lang.Object)(converter.convert((Object)(Long.valueOf($$__source.getTimestamp())),java.lang.Object.class,org.hswebframework.web.bean.FastBeanCopier.EMPTY_CLASS_ARRAY));
	if(timestamp!=null){
	$$__target.put("timestamp",timestamp);
	}
}
if(!ignore.contains("traceId")){
	if($$__source.getTraceId()!=null){
java.lang.Object traceId=(java.lang.Object)(converter.convert((Object)($$__source.getTraceId()),java.lang.Object.class,org.hswebframework.web.bean.FastBeanCopier.EMPTY_CLASS_ARRAY));
	if(traceId!=null){
	$$__target.put("traceId",traceId);
	}
	}
}
if(!ignore.contains("headers")){
	if($$__source.getHeaders()!=null){
java.lang.Object headers=(java.lang.Object)(converter.convert((Object)($$__source.getHeaders()),java.lang.Object.class,org.hswebframework.web.bean.FastBeanCopier.EMPTY_CLASS_ARRAY));
	if(headers!=null){
	$$__target.put("headers",headers);
	}
	}
}
if(!ignore.contains("ip")){
	if($$__source.getIp()!=null){
java.lang.Object ip=(java.lang.Object)(converter.convert((Object)($$__source.getIp()),java.lang.Object.class,org.hswebframework.web.bean.FastBeanCopier.EMPTY_CLASS_ARRAY));
	if(ip!=null){
	$$__target.put("ip",ip);
	}
	}
}
if(!ignore.contains("messageId")){
	if($$__source.getMessageId()!=null){
java.lang.Object messageId=(java.lang.Object)(converter.convert((Object)($$__source.getMessageId()),java.lang.Object.class,org.hswebframework.web.bean.FastBeanCopier.EMPTY_CLASS_ARRAY));
	if(messageId!=null){
	$$__target.put("messageId",messageId);
	}
	}
}
if(!ignore.contains("deviceCode")){
	if($$__source.getDeviceCode()!=null){
java.lang.Object deviceCode=(java.lang.Object)(converter.convert((Object)($$__source.getDeviceCode()),java.lang.Object.class,org.hswebframework.web.bean.FastBeanCopier.EMPTY_CLASS_ARRAY));
	if(deviceCode!=null){
	$$__target.put("deviceCode",deviceCode);
	}
	}
}
if(!ignore.contains("eventType")){
	if($$__source.getEventType()!=null){
java.lang.Object eventType=(java.lang.Object)(converter.convert((Object)($$__source.getEventType()),java.lang.Object.class,org.hswebframework.web.bean.FastBeanCopier.EMPTY_CLASS_ARRAY));
	if(eventType!=null){
	$$__target.put("eventType",eventType);
	}
	}
}
if(!ignore.contains("receiveTime")){
	if($$__source.getReceiveTime()!=null){
java.lang.Object receiveTime=(java.lang.Object)(converter.convert((Object)($$__source.getReceiveTime()),java.lang.Object.class,org.hswebframework.web.bean.FastBeanCopier.EMPTY_CLASS_ARRAY));
	if(receiveTime!=null){
	$$__target.put("receiveTime",receiveTime);
	}
	}
}
if(!ignore.contains("laneNum")){
	if($$__source.getLaneNum()!=null){
java.lang.Object laneNum=(java.lang.Object)(converter.convert((Object)($$__source.getLaneNum()),java.lang.Object.class,org.hswebframework.web.bean.FastBeanCopier.EMPTY_CLASS_ARRAY));
	if(laneNum!=null){
	$$__target.put("laneNum",laneNum);
	}
	}
}
if(!ignore.contains("speed")){
	if($$__source.getSpeed()!=null){
java.lang.Object speed=(java.lang.Object)(converter.convert((Object)($$__source.getSpeed()),java.lang.Object.class,org.hswebframework.web.bean.FastBeanCopier.EMPTY_CLASS_ARRAY));
	if(speed!=null){
	$$__target.put("speed",speed);
	}
	}
}
if(!ignore.contains("traffics")){
	if($$__source.getTraffics()!=null){
java.lang.Object traffics=(java.lang.Object)(converter.convert((Object)($$__source.getTraffics()),java.lang.Object.class,org.hswebframework.web.bean.FastBeanCopier.EMPTY_CLASS_ARRAY));
	if(traffics!=null){
	$$__target.put("traffics",traffics);
	}
	}
}
if(!ignore.contains("travelTime")){
	if($$__source.getTravelTime()!=null){
java.lang.Object travelTime=(java.lang.Object)(converter.convert((Object)($$__source.getTravelTime()),java.lang.Object.class,org.hswebframework.web.bean.FastBeanCopier.EMPTY_CLASS_ARRAY));
	if(travelTime!=null){
	$$__target.put("travelTime",travelTime);
	}
	}
}
if(!ignore.contains("occupy")){
	if($$__source.getOccupy()!=null){
java.lang.Object occupy=(java.lang.Object)(converter.convert((Object)($$__source.getOccupy()),java.lang.Object.class,org.hswebframework.web.bean.FastBeanCopier.EMPTY_CLASS_ARRAY));
	if(occupy!=null){
	$$__target.put("occupy",occupy);
	}
	}
}
if(!ignore.contains("trafficEquivalent")){
	if($$__source.getTrafficEquivalent()!=null){
java.lang.Object trafficEquivalent=(java.lang.Object)(converter.convert((Object)($$__source.getTrafficEquivalent()),java.lang.Object.class,org.hswebframework.web.bean.FastBeanCopier.EMPTY_CLASS_ARRAY));
	if(trafficEquivalent!=null){
	$$__target.put("trafficEquivalent",trafficEquivalent);
	}
	}
}
if(!ignore.contains("carSpace")){
	if($$__source.getCarSpace()!=null){
java.lang.Object carSpace=(java.lang.Object)(converter.convert((Object)($$__source.getCarSpace()),java.lang.Object.class,org.hswebframework.web.bean.FastBeanCopier.EMPTY_CLASS_ARRAY));
	if(carSpace!=null){
	$$__target.put("carSpace",carSpace);
	}
	}
}
if(!ignore.contains("bigCarTraffics")){
	if($$__source.getBigCarTraffics()!=null){
java.lang.Object bigCarTraffics=(java.lang.Object)(converter.convert((Object)($$__source.getBigCarTraffics()),java.lang.Object.class,org.hswebframework.web.bean.FastBeanCopier.EMPTY_CLASS_ARRAY));
	if(bigCarTraffics!=null){
	$$__target.put("bigCarTraffics",bigCarTraffics);
	}
	}
}
if(!ignore.contains("midCarTraffics")){
	if($$__source.getMidCarTraffics()!=null){
java.lang.Object midCarTraffics=(java.lang.Object)(converter.convert((Object)($$__source.getMidCarTraffics()),java.lang.Object.class,org.hswebframework.web.bean.FastBeanCopier.EMPTY_CLASS_ARRAY));
	if(midCarTraffics!=null){
	$$__target.put("midCarTraffics",midCarTraffics);
	}
	}
}
if(!ignore.contains("smallCarTraffics")){
	if($$__source.getSmallCarTraffics()!=null){
java.lang.Object smallCarTraffics=(java.lang.Object)(converter.convert((Object)($$__source.getSmallCarTraffics()),java.lang.Object.class,org.hswebframework.web.bean.FastBeanCopier.EMPTY_CLASS_ARRAY));
	if(smallCarTraffics!=null){
	$$__target.put("smallCarTraffics",smallCarTraffics);
	}
	}
}
if(!ignore.contains("plateType")){
	if($$__source.getPlateType()!=null){
java.lang.Object plateType=(java.lang.Object)(converter.convert((Object)($$__source.getPlateType()),java.lang.Object.class,org.hswebframework.web.bean.FastBeanCopier.EMPTY_CLASS_ARRAY));
	if(plateType!=null){
	$$__target.put("plateType",plateType);
	}
	}
}
if(!ignore.contains("recTime")){
	if($$__source.getRecTime()!=null){
java.lang.Object recTime=(java.lang.Object)(converter.convert((Object)($$__source.getRecTime()),java.lang.Object.class,org.hswebframework.web.bean.FastBeanCopier.EMPTY_CLASS_ARRAY));
	if(recTime!=null){
	$$__target.put("recTime",recTime);
	}
	}
}
}catch(Exception e){
	throw new RuntimeException(e.getMessage(),e);
}

}

javassist.CannotCompileException: [source error] no such class: com.hiscene.hilink.taixing.message.TXTriggerTrafficDataInRealTimeMessage
	at javassist.CtNewMethod.make(CtNewMethod.java:79)
	at javassist.CtNewMethod.make(CtNewMethod.java:45)
	at org.hswebframework.web.proxy.Proxy.lambda$addMethod$0(Proxy.java:73)
	at org.hswebframework.web.proxy.Proxy.handleException(Proxy.java:143)
	at org.hswebframework.web.proxy.Proxy.addMethod(Proxy.java:73)
	at org.hswebframework.web.bean.FastBeanCopier.createCopier(FastBeanCopier.java:193)
	at org.hswebframework.web.bean.FastBeanCopier.lambda$getCopier$1(FastBeanCopier.java:161)
	at java.util.concurrent.ConcurrentMap.computeIfAbsent(ConcurrentMap.java:324)
	at org.hswebframework.web.bean.FastBeanCopier.getCopier(FastBeanCopier.java:161)
	at org.hswebframework.web.bean.FastBeanCopier.copy(FastBeanCopier.java:137)
	at org.hswebframework.web.bean.FastBeanCopier.copy(FastBeanCopier.java:114)
	at org.hswebframework.web.bean.FastBeanCopier.copy(FastBeanCopier.java:101)
	at org.jetlinks.core.metadata.types.ObjectType.handle(ObjectType.java:98)
	at org.jetlinks.core.metadata.types.ObjectType.convert(ObjectType.java:118)
	at org.jetlinks.core.metadata.types.ObjectType.convert(ObjectType.java:15)
	at org.jetlinks.core.metadata.types.ArrayType.lambda$convert$1(ArrayType.java:73)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.jetlinks.core.metadata.types.ArrayType.convert(ArrayType.java:76)
	at org.jetlinks.community.device.service.data.AbstractDeviceDataStoragePolicy.fillRowPropertyValue(AbstractDeviceDataStoragePolicy.java:532)
	at org.jetlinks.community.device.service.data.AbstractDeviceDataStoragePolicy.createRowPropertyData(AbstractDeviceDataStoragePolicy.java:487)
	at org.jetlinks.community.device.service.data.AbstractDeviceDataStoragePolicy.lambda$null$24(AbstractDeviceDataStoragePolicy.java:464)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:386)
	at reactor.core.publisher.FluxIndexFuseable$IndexFuseableSubscriber.onNext(FluxIndexFuseable.java:124)
	at reactor.core.publisher.FluxIterable$IterableSubscription.slowPath(FluxIterable.java:272)
	at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:230)
	at reactor.core.publisher.FluxIndexFuseable$IndexFuseableSubscriber.request(FluxIndexFuseable.java:161)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:371)
	at reactor.core.publisher.FluxIndexFuseable$IndexFuseableSubscriber.onSubscribe(FluxIndexFuseable.java:92)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:165)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:87)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8469)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onNext(MonoFlatMapMany.java:195)
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249)
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:210)
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2398)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request(FluxPeekFuseable.java:144)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onSubscribe(MonoFlatMap.java:238)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onSubscribe(FluxPeekFuseable.java:178)
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
	at reactor.core.publisher.MonoZip$ZipCoordinator.signal(MonoZip.java:251)
	at reactor.core.publisher.MonoZip$ZipInner.onNext(MonoZip.java:336)
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:126)
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74)
	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.signalCached(MonoCacheTime.java:337)
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onNext(MonoCacheTime.java:354)
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:200)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120)
	at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82)
	at reactor.core.publisher.FluxUsingWhen$UsingWhenSubscriber.onNext(FluxUsingWhen.java:345)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120)
	at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82)
	at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.drainAsync(FluxFlattenIterable.java:421)
	at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.drain(FluxFlattenIterable.java:686)
	at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.onNext(FluxFlattenIterable.java:250)
	at reactor.core.publisher.FluxFilter$FilterSubscriber.onNext(FluxFilter.java:113)
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:220)
	at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onNext(MonoFlatMapMany.java:250)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120)
	at reactor.core.publisher.FluxDefaultIfEmpty$DefaultIfEmptySubscriber.onNext(FluxDefaultIfEmpty.java:101)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120)
	at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82)
	at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82)
	at io.lettuce.core.RedisPublisher$ImmediateSubscriber.onNext(RedisPublisher.java:886)
	at io.lettuce.core.RedisPublisher$RedisSubscription.onNext(RedisPublisher.java:291)
	at io.lettuce.core.RedisPublisher$SubscriptionCommand.doOnComplete(RedisPublisher.java:773)
	at io.lettuce.core.protocol.CommandWrapper.complete(CommandWrapper.java:65)
	at io.lettuce.core.protocol.CommandWrapper.complete(CommandWrapper.java:63)
	at io.lettuce.core.protocol.CommandHandler.complete(CommandHandler.java:746)
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:681)
	at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:598)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:750)`

**Comment by zhou-hao** [comment]
目测你不是使用的java8

**Comment by zhou-hao** [comment]
你要把协议包内部的类信息 传递到 平台。应该转为Map 后在放到对应的地方

**Comment by marshalby2** [comment]
> 你要把协议包内部的类信息 传递到 平台。应该转为Map 后在放到对应的地方

我的属性上报代码是这样写的：
`
ReportPropertyMessage reportPropertyMessage = new ReportPropertyMessage();
Map<String, Object> map = new HashMap<>();
map.put("trigger_traffic_data_in_real_time", messageList);
reportPropertyMessage.setProperties(map);
reportPropertyMessage.setDeviceId(message.getDeviceId());
reportPropertyMessage.setMessageId(IDGenerator.SNOW_FLAKE_STRING.generate());
return reportPropertyMessage;
`
其中messageList就是错误信息里找不到的实体类list

**Comment by marshalby2** [comment]
> 你要把协议包内部的类信息 传递到 平台。应该转为Map 后在放到对应的地方

我的属性上报代码是这样写的：
```
ReportPropertyMessage reportPropertyMessage = new ReportPropertyMessage();
Map<String, Object> map = new HashMap<>();
map.put("trigger_traffic_data_in_real_time", messageList);
reportPropertyMessage.setProperties(map);
reportPropertyMessage.setDeviceId(message.getDeviceId());
reportPropertyMessage.setMessageId(IDGenerator.SNOW_FLAKE_STRING.generate());
return reportPropertyMessage;
```
其中messageList就是错误信息里找不到的实体类list

**Comment by zhou-hao** [comment]
messageList 里不要放实体类

**Comment by marshalby2** [comment]
> 

那如果我要上报的属性是array类型，我应该怎么做

**Comment by zhou-hao** [comment]
List里放 Map。 把你的实体类转为Map。

**Comment by marshalby2** [comment]
> List里放 Map。 把你的实体类转为Map。

好的，谢谢
