### ISSUE TITLE
数据库脚本有吗？

### ISSUE THREAD

**Issue by xiaowangzi1988** [jetlinks/jetlinks-community#22]
Caused by: io.r2dbc.postgresql.ExceptionFactory$PostgresqlNonTransientResourceException: ���ݿ� "jetlinks" ������
	at io.r2dbc.postgresql.ExceptionFactory.createException(ExceptionFactory.java:98)
	at io.r2dbc.postgresql.ExceptionFactory.handleErrorResponse(ExceptionFactory.java:110)
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:96)
	... 37 common frames omitted

运行开源版报以上错误，postgresql数据库脚本有吗？

**Comment by zhou-hao** [comment]
需要手动创建名为jetlinks的库。或者修改配置文件



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: xiaowangzi1988 <notifications@github.com&gt;
发送时间: 2020年9月29日 11:05
收件人: jetlinks/jetlinks-community <jetlinks-community@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[jetlinks/jetlinks-community] 数据库脚本有吗？ (#22)





 
Caused by: io.r2dbc.postgresql.ExceptionFactory$PostgresqlNonTransientResourceException:    ݿ  "jetlinks"       
 at io.r2dbc.postgresql.ExceptionFactory.createException(ExceptionFactory.java:98)
 at io.r2dbc.postgresql.ExceptionFactory.handleErrorResponse(ExceptionFactory.java:110)
 at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:96)
 ... 37 common frames omitted
 
运行开源版报以上错误，postgresql数据库脚本有吗？
