### ISSUE TITLE
使用内嵌的es，重启后es读取报错。

### ISSUE THREAD

**Issue by msj100f** [jetlinks/jetlinks-community#265]
测试阶段，使用内嵌的es，几乎每次重启都会报错，偶尔一次不会。

```
2023-04-15 17:01:20.985  WARN 10866 --- [           main] onfigReactiveWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'alarmTaskExecutorProvider' defined in class path resource [org/jetlinks/community/rule/engine/alarm/AlarmTaskExecutorProvider.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'defaultAlarmRuleHandler' defined in class path resource [org/jetlinks/community/rule/engine/alarm/DefaultAlarmRuleHandler.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'alarmHistoryService' defined in class path resource [org/jetlinks/community/rule/engine/configuration/RuleEngineManagerConfiguration$ElasticSearchAlarmHistoryConfiguration.class]: Invocation of init method failed; nested exception is java.lang.IllegalStateException: Timeout on blocking read for 10000000000 NANOSECONDS
2023-04-15 17:01:28.017  INFO 10866 --- [           main] io.scalecube.cluster.Cluster             : [default:default:82786f88-a447-436b-8f85-42f44ec12aca@172.27.35.224:37074][doShutdown] Shutting down
2023-04-15 17:01:28.022  INFO 10866 --- [           main] io.scalecube.cluster.Cluster             : [default:default:82786f88-a447-436b-8f85-42f44ec12aca@172.27.35.224:37074][leaveCluster] Leaving cluster
2023-04-15 17:01:28.044  WARN 10866 --- [           main] d.r.c.l.LettucePoolingConnectionProvider : LettucePoolingConnectionProvider contains unreleased connections
2023-04-15 17:01:28.501 ERROR 10866 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'alarmTaskExecutorProvider' defined in class path resource [org/jetlinks/community/rule/engine/alarm/AlarmTaskExecutorProvider.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'defaultAlarmRuleHandler' defined in class path resource [org/jetlinks/community/rule/engine/alarm/DefaultAlarmRuleHandler.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'alarmHistoryService' defined in class path resource [org/jetlinks/community/rule/engine/configuration/RuleEngineManagerConfiguration$ElasticSearchAlarmHistoryConfiguration.class]: Invocation of init method failed; nested exception is java.lang.IllegalStateException: Timeout on blocking read for 10000000000 NANOSECONDS
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:66)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
	at org.jetlinks.community.standalone.JetLinksApplication.main(JetLinksApplication.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'defaultAlarmRuleHandler' defined in class path resource [org/jetlinks/community/rule/engine/alarm/DefaultAlarmRuleHandler.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'alarmHistoryService' defined in class path resource [org/jetlinks/community/rule/engine/configuration/RuleEngineManagerConfiguration$ElasticSearchAlarmHistoryConfiguration.class]: Invocation of init method failed; nested exception is java.lang.IllegalStateException: Timeout on blocking read for 10000000000 NANOSECONDS
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
	... 27 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'alarmHistoryService' defined in class path resource [org/jetlinks/community/rule/engine/configuration/RuleEngineManagerConfiguration$ElasticSearchAlarmHistoryConfiguration.class]: Invocation of init method failed; nested exception is java.lang.IllegalStateException: Timeout on blocking read for 10000000000 NANOSECONDS
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
	... 41 common frames omitted
Caused by: java.lang.IllegalStateException: Timeout on blocking read for 10000000000 NANOSECONDS
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:123)
	at reactor.core.publisher.Mono.block(Mono.java:1731)
	at org.jetlinks.community.rule.engine.service.ElasticSearchAlarmHistoryService.init(ElasticSearchAlarmHistoryService.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1930)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1872)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)
	... 52 common frames omitted
```

**Comment by zhou-hao** [comment]
单独安装es试试

**Comment by msj100f** [comment]
这个是具体报错的位置，和数据有关系吗？
```
2023-04-24 21:37:15.022  WARN 5600 --- [           main] onfigReactiveWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'alarmTaskExecutorProvider' defined in class path resource [org/jetlinks/community/rule/engine/alarm/AlarmTaskExecutorProvider.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'defaultAlarmRuleHandler' defined in class path resource [org/jetlinks/community/rule/engine/alarm/DefaultAlarmRuleHandler.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'alarmHistoryService' defined in class path resource [org/jetlinks/community/rule/engine/configuration/RuleEngineManagerConfiguration$ElasticSearchAlarmHistoryConfiguration.class]: Invocation of init method failed; nested exception is java.lang.IllegalStateException: Timeout on blocking read for 10000000000 NANOSECONDS
2023-04-24 21:37:15.102  WARN 5600 --- [or-http-epoll-2] r.netty.http.client.HttpClientConnect    : [f931c81f-4, L:/127.0.0.1:36446 - R:localhost/127.0.0.1:9200] The connection observed an error

io.netty.handler.timeout.ReadTimeoutException: null

保存ElasticSearch数据失败:
org.springframework.web.reactive.function.client.WebClientRequestException: nested exception is io.netty.handler.timeout.ReadTimeoutException
	at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.lambda$wrapException$9(ExchangeFunctions.java:141)
	Suppressed: The stacktrace has been enhanced by Reactor, refer to additional information below:
Assembly trace from producer [reactor.core.publisher.MonoErrorSupplied] :
	reactor.core.publisher.Mono.error(Mono.java:330)
	org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.wrapException(ExchangeFunctions.java:141)
Error has been observed at the following site(s):
	*__________Mono.error ⇢ at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.wrapException(ExchangeFunctions.java:141)
	*__Mono.onErrorResume ⇢ at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.exchange(ExchangeFunctions.java:106)
	|_           Mono.map ⇢ at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.exchange(ExchangeFunctions.java:107)
	|_     Mono.doOnError ⇢ at org.springframework.data.elasticsearch.client.reactive.DefaultWebClientProvider.lambda$createWebClientForSocketAddress$3(DefaultWebClientProvider.java:187)
	|_         checkpoint ⇢ Request to POST http://localhost:9200/_bulk?timeout=9s [DefaultWebClient]
	|_ Mono.switchIfEmpty ⇢ at org.springframework.web.reactive.function.client.DefaultWebClient$DefaultRequestBodyUriSpec.lambda$exchange$7(DefaultWebClient.java:433)
	*__________Mono.defer ⇢ at org.springframework.web.reactive.function.client.DefaultWebClient$DefaultRequestBodyUriSpec.exchange(DefaultWebClient.java:430)
	|_   Mono.flatMapMany ⇢ at org.springframework.web.reactive.function.client.DefaultWebClient$DefaultRequestBodyUriSpec.exchangeToFlux(DefaultWebClient.java:412)
	*____Mono.flatMapMany ⇢ at org.jetlinks.community.elastic.search.service.reactive.DefaultReactiveElasticsearchClient.sendRequest(DefaultReactiveElasticsearchClient.java:823)
	*____Flux.publishNext ⇢ at org.jetlinks.community.elastic.search.service.reactive.DefaultReactiveElasticsearchClient.bulk(DefaultReactiveElasticsearchClient.java:574)
	*________Mono.flatMap ⇢ at org.jetlinks.community.elastic.search.service.reactive.ReactiveElasticSearchService.doSave(ReactiveElasticSearchService.java:478)
Original Stack Trace:
		at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.lambda$wrapException$9(ExchangeFunctions.java:141)
		at reactor.core.publisher.MonoErrorSupplied.subscribe(MonoErrorSupplied.java:55)
		at reactor.core.publisher.Mono.subscribe(Mono.java:4397)
		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103)
		at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onError(FluxPeekFuseable.java:234)
```

**Comment by zhou-hao** [comment]
es地址改成127.0.0.1试试

**Comment by msj100f** [comment]
> es地址改成127.0.0.1试试

改了还是不行，我部署了个单节点的es，还是这个问题，删掉报错的 index，就可以了，有时候是 alarm_history这个索引不行，有时候是 device_message的不行，删掉就正常了。

**Comment by zhou-hao** [comment]
emm es是什么版本，怎么安装的

**Comment by msj100f** [comment]
版本：7.17.9
es配置：
node.name: node-1
path.data: /home/elasticsearch/elasticsearch-7.17.9/data
path.logs: /home/elasticsearch/elasticsearch-7.17.9/logs
bootstrap.memory_lock: true
network.host: 127.0.0.1
http.port: 9200
discovery.type: single-node

**Comment by zhou-hao** [comment]
network.host 改成  0.0.0.0或者内网ip试试呢

**Comment by msj100f** [comment]
> network.host 改成 0.0.0.0或者内网ip试试呢

我试试

**Comment by msj100f** [comment]
可以了
