### ISSUE TITLE
spring boot Application run failed

### ISSUE THREAD

**Issue by lc991219** [jetlinks/jetlinks-community#27]
2020-12-09 09:28:54.592 ERROR 1592 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Could not register object [org.springdoc.core.GroupedOpenApi@2489e84a] under bean name '': there is already object [org.springdoc.core.GroupedOpenApi@2a39aa2b] bound
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.registerSingleton(DefaultSingletonBeanRegistry.java:124)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.registerSingleton(DefaultListableBeanFactory.java:1078)
	at org.springdoc.core.SpringdocBeanFactoryConfigurer.lambda$postProcessBeanFactory$1(SpringdocBeanFactoryConfigurer.java:76)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.springdoc.core.SpringdocBeanFactoryConfigurer.postProcessBeanFactory(SpringdocBeanFactoryConfigurer.java:76)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:291)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:182)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:707)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:533)
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:62)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at org.jetlinks.community.standalone.JetLinksApplication.main(JetLinksApplication.java:33)

Process finished with exit code 1

**Comment by zhou-hao** [comment]
文档配置哪里有问题吧，检查springdoc.group-configs相关配置
