### ISSUE TITLE
ce exit 1

### ISSUE THREAD

**Issue by cooper1025** [jetlinks/jetlinks-community#294]
Hi @zhou-hao ,
run jetlinks in docker(path/to/git/docker/run-all) with docker-compose, jetlinks-ce failed for es unreachable.
I have tried to change host 'elasticsearch:9200' to localhost/0.0.0.0/127.0.0.1/docker bridge intl addr, it still not work.
Thx for your work.

**Comment by cooper1025** [comment]
```
jetlinks-ce-elasticsearch | [2023-05-24T03:30:06,338][WARN ][o.e.b.JNANatives         ] [unknown] Unable to lock JVM Memory: error=12, reason=Cannot allocate memory
jetlinks-ce-elasticsearch | [2023-05-24T03:30:06,340][WARN ][o.e.b.JNANatives         ] [unknown] This can result in part of the JVM being swapped out.
jetlinks-ce-elasticsearch | [2023-05-24T03:30:06,340][WARN ][o.e.b.JNANatives         ] [unknown] Increase RLIMIT_MEMLOCK, soft limit: 65536, hard limit: 65536
jetlinks-ce-elasticsearch | [2023-05-24T03:30:06,341][WARN ][o.e.b.JNANatives         ] [unknown] These can be adjusted by modifying /etc/security/limits.conf, for example: 
jetlinks-ce-elasticsearch | 	# allow user 'elasticsearch' mlockall
jetlinks-ce-elasticsearch | 	elasticsearch soft memlock unlimited
jetlinks-ce-elasticsearch | 	elasticsearch hard memlock unlimited
jetlinks-ce-elasticsearch | [2023-05-24T03:30:06,341][WARN ][o.e.b.JNANatives         ] [unknown] If you are logged in interactively, you will have to re-login for the new limits to take effect.
jetlinks-ce-elasticsearch | [2023-05-24T03:30:06,605][INFO ][o.e.e.NodeEnvironment    ] [kRQrQM3] using [1] data paths, mounts [[/ (overlay)]], net usable_space [400.1gb], net total_space [1.7tb], types [overlay]
jetlinks-ce-elasticsearch | [2023-05-24T03:30:06,606][INFO ][o.e.e.NodeEnvironment    ] [kRQrQM3] heap size [1gb], compressed ordinary object pointers [true]
jetlinks-ce-elasticsearch | [2023-05-24T03:30:06,608][INFO ][o.e.n.Node               ] [kRQrQM3] node name derived from node ID [kRQrQM3KTJm4OxvlXWcAfg]; set [node.name] to override
jetlinks-ce-elasticsearch | [2023-05-24T03:30:06,608][INFO ][o.e.n.Node               ] [kRQrQM3] version[6.8.11], pid[1], build[default/docker/00bf386/2020-07-09T19:08:08.940669Z], OS[Linux/5.15.0-71-generic/amd64], JVM[AdoptOpenJDK/OpenJDK 64-Bit Server VM/14.0.1/14.0.1+7]
jetlinks-ce-elasticsearch | [2023-05-24T03:30:06,608][INFO ][o.e.n.Node               ] [kRQrQM3] JVM arguments [-Xms1g, -Xmx1g, -XX:+UseG1GC, -XX:G1ReservePercent=25, -XX:InitiatingHeapOccupancyPercent=30, -Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -XX:+ShowCodeDetailsInExceptionMessages, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.io.tmpdir=/tmp/elasticsearch-13568296827728981933, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Djava.locale.providers=COMPAT, -XX:UseAVX=2, -Des.cgroups.hierarchy.override=/, -Djava.net.preferIPv4Stack=true, -Xms1g, -Xmx1g, -Des.path.home=/usr/share/elasticsearch, -Des.path.conf=/usr/share/elasticsearch/config, -Des.distribution.flavor=default, -Des.distribution.type=docker]
jetlinks-ce      |       _      _   _      _       _
jetlinks-ce      |      | |    | | | |    (_)     | |
jetlinks-ce      |      | | ___| |_| |     _ _ __ | | _____
jetlinks-ce      |  _   | |/ _ \ __| |    | | '_ \| |/ / __|
jetlinks-ce      | | |__| |  __/ |_| |____| | | | |   <\__ \
jetlinks-ce      |  \____/ \___|\__|______|_|_| |_|_|\_\___/
jetlinks-ce      |   jetlinks       2.0.0-SNAPSHOT  build 2023-04-18 07:52:58
jetlinks-ce      |   spring-boot    2.7.3
jetlinks-ce      |   http port      8848
jetlinks-ce      |   redis          redis:6379
jetlinks-ce      |   r2dbc          r2dbc:postgresql://postgres:5432/jetlinks
jetlinks-ce-elasticsearch | [2023-05-24T03:30:08,202][INFO ][o.e.p.PluginsService     ] [kRQrQM3] loaded module [aggs-matrix-stats]
jetlinks-ce-elasticsearch | [2023-05-24T03:30:08,202][INFO ][o.e.p.PluginsService     ] [kRQrQM3] loaded module [analysis-common]
jetlinks-ce-elasticsearch | [2023-05-24T03:30:08,202][INFO ][o.e.p.PluginsService     ] [kRQrQM3] loaded module [ingest-common]
jetlinks-ce-elasticsearch | [2023-05-24T03:30:08,202][INFO ][o.e.p.PluginsService     ] [kRQrQM3] loaded module [ingest-geoip]
jetlinks-ce-elasticsearch | [2023-05-24T03:30:08,202][INFO ][o.e.p.PluginsService     ] [kRQrQM3] loaded module [ingest-user-agent]
jetlinks-ce-elasticsearch | [2023-05-24T03:30:08,202][INFO ][o.e.p.PluginsService     ] [kRQrQM3] loaded module [lang-expression]
jetlinks-ce-elasticsearch | [2023-05-24T03:30:08,202][INFO ][o.e.p.PluginsService     ] [kRQrQM3] loaded module [lang-mustache]
jetlinks-ce-elasticsearch | [2023-05-24T03:30:08,202][INFO ][o.e.p.PluginsService     ] [kRQrQM3] loaded module [lang-painless]
jetlinks-ce-elasticsearch | [2023-05-24T03:30:08,203][INFO ][o.e.p.PluginsService     ] [kRQrQM3] loaded module [mapper-extras]
jetlinks-ce-elasticsearch | [2023-05-24T03:30:08,203][INFO ][o.e.p.PluginsService     ] [kRQrQM3] loaded module [parent-join]
jetlinks-ce-elasticsearch | [2023-05-24T03:30:08,203][INFO ][o.e.p.PluginsService     ] [kRQrQM3] loaded module [percolator]
jetlinks-ce-elasticsearch | [2023-05-24T03:30:08,203][INFO ][o.e.p.PluginsService     ] [kRQrQM3] loaded module [rank-eval]
jetlinks-ce-elasticsearch | [2023-05-24T03:30:08,203][INFO ][o.e.p.PluginsService     ] [kRQrQM3] loaded module [reindex]
jetlinks-ce-elasticsearch | [2023-05-24T03:30:08,203][INFO ][o.e.p.PluginsService     ] [kRQrQM3] loaded module [repository-url]
jetlinks-ce-elasticsearch | [2023-05-24T03:30:08,203][INFO ][o.e.p.PluginsService     ] [kRQrQM3] loaded module [transport-netty4]
jetlinks-ce-elasticsearch | [2023-05-24T03:30:08,203][INFO ][o.e.p.PluginsService     ] [kRQrQM3] loaded module [tribe]
jetlinks-ce-elasticsearch | [2023-05-24T03:30:08,203][INFO ][o.e.p.PluginsService     ] [kRQrQM3] loaded module [x-pack-ccr]
jetlinks-ce-elasticsearch | [2023-05-24T03:30:08,203][INFO ][o.e.p.PluginsService     ] [kRQrQM3] loaded module [x-pack-core]
jetlinks-ce-elasticsearch | [2023-05-24T03:30:08,204][INFO ][o.e.p.PluginsService     ] [kRQrQM3] loaded module [x-pack-deprecation]
jetlinks-ce-elasticsearch | [2023-05-24T03:30:08,204][INFO ][o.e.p.PluginsService     ] [kRQrQM3] loaded module [x-pack-graph]
jetlinks-ce-elasticsearch | [2023-05-24T03:30:08,204][INFO ][o.e.p.PluginsService     ] [kRQrQM3] loaded module [x-pack-ilm]
jetlinks-ce-elasticsearch | [2023-05-24T03:30:08,204][INFO ][o.e.p.PluginsService     ] [kRQrQM3] loaded module [x-pack-logstash]
jetlinks-ce-elasticsearch | [2023-05-24T03:30:08,204][INFO ][o.e.p.PluginsService     ] [kRQrQM3] loaded module [x-pack-ml]
jetlinks-ce-elasticsearch | [2023-05-24T03:30:08,204][INFO ][o.e.p.PluginsService     ] [kRQrQM3] loaded module [x-pack-monitoring]
jetlinks-ce-elasticsearch | [2023-05-24T03:30:08,204][INFO ][o.e.p.PluginsService     ] [kRQrQM3] loaded module [x-pack-rollup]
jetlinks-ce-elasticsearch | [2023-05-24T03:30:08,204][INFO ][o.e.p.PluginsService     ] [kRQrQM3] loaded module [x-pack-security]
jetlinks-ce-elasticsearch | [2023-05-24T03:30:08,205][INFO ][o.e.p.PluginsService     ] [kRQrQM3] loaded module [x-pack-sql]
jetlinks-ce-elasticsearch | [2023-05-24T03:30:08,205][INFO ][o.e.p.PluginsService     ] [kRQrQM3] loaded module [x-pack-upgrade]
jetlinks-ce-elasticsearch | [2023-05-24T03:30:08,205][INFO ][o.e.p.PluginsService     ] [kRQrQM3] loaded module [x-pack-watcher]
jetlinks-ce-elasticsearch | [2023-05-24T03:30:08,205][INFO ][o.e.p.PluginsService     ] [kRQrQM3] no plugins loaded
jetlinks-ce-elasticsearch | [2023-05-24T03:30:11,715][INFO ][o.e.x.s.a.s.FileRolesStore] [kRQrQM3] parsed [0] roles from file [/usr/share/elasticsearch/config/roles.yml]
jetlinks-ce-elasticsearch | [2023-05-24T03:30:12,376][INFO ][o.e.x.m.p.l.CppLogMessageHandler] [kRQrQM3] [controller/96] [Main.cc@114] controller (64 bit): Version 6.8.11 (Build e37136453cd38f) Copyright (c) 2020 Elasticsearch BV
jetlinks-ce-elasticsearch | [2023-05-24T03:30:12,977][INFO ][o.e.d.DiscoveryModule    ] [kRQrQM3] using discovery type [single-node] and host providers [settings]
jetlinks-ce      | 2023-05-24 11:30:13.361  WARN 7 --- [           main] onfigReactiveWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'defaultNotifierManager' defined in class path resource [org/jetlinks/community/notify/DefaultNotifierManager.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'notifyConfigManager' defined in class path resource [org/jetlinks/community/notify/configuration/NotifierAutoConfiguration.class]: Unsatisfied dependency expressed through method 'notifyConfigManager' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'defaultNotifyConfigManager': Unsatisfied dependency expressed through field 'configService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'notifyConfigService': Unsatisfied dependency expressed through field 'cacheManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'reactiveCacheManager' defined in class path resource [org/hswebframework/web/cache/configuration/ReactiveCacheManagerConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.hswebframework.web.cache.ReactiveCacheManager]: Factory method 'reactiveCacheManager' threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'reactiveRedisTemplate' defined in class path resource [org/jetlinks/community/configure/redis/RedisSerializationConfiguration.class]: Unsatisfied dependency expressed through method 'reactiveRedisTemplate' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'redisConnectionFactory' defined in class path resource [org/springframework/boot/autoconfigure/data/redis/LettuceConnectionConfiguration.class]: Unsatisfied dependency expressed through method 'redisConnectionFactory' parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'lettuceClientResources' defined in class path resource [org/springframework/boot/autoconfigure/data/redis/LettuceConnectionConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.lettuce.core.resource.DefaultClientResources]: Factory method 'lettuceClientResources' threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'lettuceMetrics' defined in class path resource [org/springframework/boot/actuate/autoconfigure/metrics/redis/LettuceMetricsAutoConfiguration.class]: Unsatisfied dependency expressed through method 'lettuceMetrics' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'meterRegistry' defined in class path resource [org/jetlinks/community/timeseries/micrometer/TimeSeriesMeterRegistryConfiguration.class]: Unsatisfied dependency expressed through method 'meterRegistry' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'timeSeriesMeterRegistrySupplier' defined in class path resource [org/jetlinks/community/timeseries/micrometer/TimeSeriesMeterRegistryConfiguration.class]: Unsatisfied dependency expressed through method 'timeSeriesMeterRegistrySupplier' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'elasticSearchTimeSeriesManager' defined in class path resource [org/jetlinks/community/elastic/search/configuration/ElasticSearchConfiguration.class]: Unsatisfied dependency expressed through method 'elasticSearchTimeSeriesManager' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'elasticSearchIndexManager' defined in class path resource [org/jetlinks/community/elastic/search/configuration/ElasticSearchConfiguration.class]: Unsatisfied dependency expressed through method 'elasticSearchIndexManager' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'timeByDayElasticSearchIndexStrategy' defined in class path resource [org/jetlinks/community/elastic/search/index/strategies/TimeByDayElasticSearchIndexStrategy.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'defaultReactiveElasticsearchClient' defined in class path resource [org/jetlinks/community/elastic/search/configuration/ElasticSearchConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.jetlinks.community.elastic.search.service.reactive.DefaultReactiveElasticsearchClient]: Factory method 'defaultReactiveElasticsearchClient' threw exception; nested exception is org.springframework.data.elasticsearch.client.NoReachableHostException: Host 'elasticsearch:9200' not reachable. Cluster state is offline.
jetlinks-ce      | 2023-05-24 11:30:13.472 ERROR 7 --- [           main] o.s.boot.SpringApplication               : Application run failed
jetlinks-ce      | 
jetlinks-ce      | org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'defaultNotifierManager' defined in class path resource [org/jetlinks/community/notify/DefaultNotifierManager.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'notifyConfigManager' defined in class path resource [org/jetlinks/community/notify/configuration/NotifierAutoConfiguration.class]: Unsatisfied dependency expressed through method 'notifyConfigManager' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'defaultNotifyConfigManager': Unsatisfied dependency expressed through field 'configService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'notifyConfigService': Unsatisfied dependency expressed through field 'cacheManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'reactiveCacheManager' defined in class path resource [org/hswebframework/web/cache/configuration/ReactiveCacheManagerConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.hswebframework.web.cache.ReactiveCacheManager]: Factory method 'reactiveCacheManager' threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'reactiveRedisTemplate' defined in class path resource [org/jetlinks/community/configure/redis/RedisSerializationConfiguration.class]: Unsatisfied dependency expressed through method 'reactiveRedisTemplate' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'redisConnectionFactory' defined in class path resource [org/springframework/boot/autoconfigure/data/redis/LettuceConnectionConfiguration.class]: Unsatisfied dependency expressed through method 'redisConnectionFactory' parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'lettuceClientResources' defined in class path resource [org/springframework/boot/autoconfigure/data/redis/LettuceConnectionConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.lettuce.core.resource.DefaultClientResources]: Factory method 'lettuceClientResources' threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'lettuceMetrics' defined in class path resource [org/springframework/boot/actuate/autoconfigure/metrics/redis/LettuceMetricsAutoConfiguration.class]: Unsatisfied dependency expressed through method 'lettuceMetrics' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'meterRegistry' defined in class path resource [org/jetlinks/community/timeseries/micrometer/TimeSeriesMeterRegistryConfiguration.class]: Unsatisfied dependency expressed through method 'meterRegistry' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'timeSeriesMeterRegistrySupplier' defined in class path resource [org/jetlinks/community/timeseries/micrometer/TimeSeriesMeterRegistryConfiguration.class]: Unsatisfied dependency expressed through method 'timeSeriesMeterRegistrySupplier' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'elasticSearchTimeSeriesManager' defined in class path resource [org/jetlinks/community/elastic/search/configuration/ElasticSearchConfiguration.class]: Unsatisfied dependency expressed through method 'elasticSearchTimeSeriesManager' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'elasticSearchIndexManager' defined in class path resource [org/jetlinks/community/elastic/search/configuration/ElasticSearchConfiguration.class]: Unsatisfied dependency expressed through method 'elasticSearchIndexManager' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'timeByDayElasticSearchIndexStrategy' defined in class path resource [org/jetlinks/community/elastic/search/index/strategies/TimeByDayElasticSearchIndexStrategy.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'defaultReactiveElasticsearchClient' defined in class path resource [org/jetlinks/community/elastic/search/configuration/ElasticSearchConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.jetlinks.community.elastic.search.service.reactive.DefaultReactiveElasticsearchClient]: Factory method 'defaultReactiveElasticsearchClient' threw exception; nested exception is org.springframework.data.elasticsearch.client.NoReachableHostException: Host 'elasticsearch:9200' not reachable. Cluster state is offline.
jetlinks-ce      | 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
jetlinks-ce      | 	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229)
jetlinks-ce      | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)
jetlinks-ce      | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)
jetlinks-ce      | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
jetlinks-ce      | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
jetlinks-ce      | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
jetlinks-ce      | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
jetlinks-ce      | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
jetlinks-ce      | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:213)
jetlinks-ce      | 	at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:270)
jetlinks-ce      | 	at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:762)
jetlinks-ce      | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:567)
jetlinks-ce      | 	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:66)
jetlinks-ce      | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734)
jetlinks-ce      | 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
jetlinks-ce      | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
jetlinks-ce      | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
jetlinks-ce      | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
jetlinks-ce      | 	at org.jetlinks.community.standalone.JetLinksApplication.main(JetLinksApplication.java:33)
jetlinks-ce      | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jetlinks-ce      | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
jetlinks-ce      | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
jetlinks-ce      | 	at java.lang.reflect.Method.invoke(Method.java:498)
jetlinks-ce      | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
jetlinks-ce      | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
jetlinks-ce      | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
jetlinks-ce      | 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)

```

**Comment by zhou-hao** [comment]
单独部署elasticsearch试试
