### ISSUE TITLE
遇到 ClassNotFoundException 

### ISSUE THREAD

**Issue by MoonBottle** [jetlinks/jetlinks-community#439]
org.jetlinks.community.device.service.LocalDeviceInstanceService#mergeConfiguration

方法报错如下：
```java
java.lang.ClassNotFoundException: [Lorg/jetlinks/community/device/enums/DeviceFeature
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.hswebframework.ezorm.core.SerializedLambda.getImplClass(SerializedLambda.java:39)
	at org.hswebframework.ezorm.core.MethodReferenceConverter.lambda$parse$0(MethodReferenceConverter.java:34)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1688)
	at org.hswebframework.ezorm.core.MethodReferenceConverter.parse(MethodReferenceConverter.java:25)
	at org.hswebframework.ezorm.core.MethodReferenceConverter.convertToColumn(MethodReferenceConverter.java:39)
	at org.hswebframework.ezorm.core.MethodReferenceConverter.convertToColumn(MethodReferenceConverter.java:13)
	at org.hswebframework.ezorm.core.MethodReferenceColumn.getColumn(MethodReferenceColumn.java:27)
	at org.hswebframework.ezorm.rdb.mapping.DSLUpdate.set(DSLUpdate.java:163)
	at org.jetlinks.community.device.service.LocalDeviceInstanceService.lambda$mergeConfiguration$84(LocalDeviceInstanceService.java:931)
```
 debug 看了下，最终执行的 org.hswebframework.ezorm.core.SerializedLambda#getImplClass 中的以下这行代码
```java
implClassResolved = Class.forName(className.replace('/', '.'));
```

className 为 [Lorg/jetlinks/community/device/enums/DeviceFeature ，最终报错
已确认 org/jetlinks/community/device/enums/DeviceFeature 这个类是有的

![image](https://github.com/jetlinks/jetlinks-community/assets/12904505/818de612-ddad-495a-bd9e-3c74ac7cb165)

![image](https://github.com/jetlinks/jetlinks-community/assets/12904505/db222d03-ad29-4162-9104-9048781c1073)

**Comment by zhou-hao** [comment]
用的哪个版本

**Comment by zhou-hao** [comment]
升级到4.1.2-SNAPSHOT 试试？

**Comment by MoonBottle** [comment]
![image](https://github.com/jetlinks/jetlinks-community/assets/12904505/b1165907-4964-4612-8f8c-ef021166edfa)
升级了，还是会有报错

**Comment by MoonBottle** [comment]
![image](https://github.com/jetlinks/jetlinks-community/assets/12904505/baec3389-6737-4353-be7a-96f767672f96)
好像是数组的问题？

**Comment by zhou-hao** [comment]
已修复，刷新maven试试。 https://github.com/hs-web/hsweb-easy-orm/pull/59

**Comment by MoonBottle** [comment]
可以了，棒 👍
