### ISSUE TITLE
jetlinks启动时，连接数据库报错

### ISSUE THREAD

**Issue by wallace1** [jetlinks/jetlinks-community#475]
jetlinks安装好mysql5.7、redis和jetlinks以后，mysql和redis启动正常。在启动jetlinks时报如下错误：
```bash
2024-03-01 13:51:32,348 34049 [main] DEBUG o.h.e.c.meta.AbstractSchemaMetadata - load table metadata ,use parser:MysqlTableMetadataParser
2024-03-01 13:51:32,907 34608 [reactor-tcp-epoll-4] WARN  d.m.r.m.client.MessageDuplexCodec - Connection has been closed by peer
2024-03-01 13:51:32,907 34608 [reactor-tcp-epoll-1] WARN  d.m.r.m.client.MessageDuplexCodec - Connection has been closed by peer
2024-03-01 13:51:32,908 34609 [reactor-tcp-epoll-6] WARN  d.m.r.m.client.MessageDuplexCodec - Connection has been closed by peer
2024-03-01 13:51:32,908 34609 [reactor-tcp-epoll-7] WARN  d.m.r.m.client.MessageDuplexCodec - Connection has been closed by peer
2024-03-01 13:51:32,908 34609 [reactor-tcp-epoll-8] WARN  d.m.r.m.client.MessageDuplexCodec - Connection has been closed by peer
2024-03-01 13:51:32,909 34610 [reactor-tcp-epoll-3] WARN  d.m.r.m.client.MessageDuplexCodec - Connection has been closed by peer
2024-03-01 13:51:32,909 34610 [reactor-tcp-epoll-2] WARN  d.m.r.m.client.MessageDuplexCodec - Connection has been closed by peer
2024-03-01 13:51:32,909 34610 [reactor-tcp-epoll-5] WARN  d.m.r.m.client.MessageDuplexCodec - Connection has been closed by peer
2024-03-01 13:51:32,953 34654 [reactor-tcp-epoll-2] WARN  d.m.r.m.client.MessageDuplexCodec - Connection has been closed by peer
2024-03-01 13:51:32,978 34679 [reactor-tcp-epoll-1] WARN  d.m.r.m.client.MessageDuplexCodec - Connection has been closed by peer
2024-03-01 13:51:33,004 34705 [reactor-tcp-epoll-1] WARN  d.m.r.m.client.MessageDuplexCodec - Connection has been closed by peer
2024-03-01 13:51:33,007 34708 [reactor-tcp-epoll-1] WARN  d.m.r.m.client.MessageDuplexCodec - Connection has been closed by peer
2024-03-01 13:51:33,009 34710 [reactor-tcp-epoll-1] WARN  d.m.r.m.client.MessageDuplexCodec - Connection has been closed by peer
2024-03-01 13:51:33,010 34711 [reactor-tcp-epoll-1] WARN  d.m.r.m.client.MessageDuplexCodec - Connection has been closed by peer
2024-03-01 13:51:33,011 34712 [reactor-tcp-epoll-1] WARN  d.m.r.m.client.MessageDuplexCodec - Connection has been closed by peer
2024-03-01 13:51:33,012 34713 [reactor-tcp-epoll-1] WARN  d.m.r.m.client.MessageDuplexCodec - Connection has been closed by peer
2024-03-01 13:51:33,013 34714 [reactor-tcp-epoll-1] WARN  d.m.r.m.client.MessageDuplexCodec - Connection has been closed by peer
2024-03-01 13:51:33,015 34716 [reactor-tcp-epoll-1] WARN  d.m.r.m.client.MessageDuplexCodec - Connection has been closed by peer
2024-03-01 13:51:33,058 34759 [main] ERROR o.s.boot.SpringApplication - Application run failed
java.lang.IllegalStateException: Failed to execute CommandLineRunner
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:787)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:768)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
        at org.iotlinks.standalone.IoTLinksApplication.main(IoTLinksApplication.java:34)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:597)
Caused by: java.util.concurrent.ExecutionException: java.util.NoSuchElementException: Flux#last() didn't observe any onNext signal
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928)
        at org.hswebframework.ezorm.rdb.executor.reactive.ReactiveSyncSqlExecutor.select(ReactiveSyncSqlExecutor.java:40)
        at org.hswebframework.ezorm.rdb.supports.commons.RDBTableMetadataParser.tableExists(RDBTableMetadataParser.java:101)
        at org.hswebframework.ezorm.rdb.supports.commons.RDBTableMetadataParser.parseByName(RDBTableMetadataParser.java:88)
        at org.hswebframework.ezorm.core.meta.AbstractSchemaMetadata.lambda$loadMetadata$1(AbstractSchemaMetadata.java:75)
        at java.util.Optional.flatMap(Optional.java:241)
        at org.hswebframework.ezorm.core.meta.AbstractSchemaMetadata.loadMetadata(AbstractSchemaMetadata.java:73)
        at org.hswebframework.ezorm.rdb.metadata.RDBSchemaMetadata.loadMetadata(RDBSchemaMetadata.java:136)
        at org.hswebframework.ezorm.core.meta.AbstractSchemaMetadata.lambda$null$6(AbstractSchemaMetadata.java:111)
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
        at org.hswebframework.ezorm.core.meta.AbstractSchemaMetadata.lambda$getObject$7(AbstractSchemaMetadata.java:111)
        at java.util.Optional.map(Optional.java:215)
        at org.hswebframework.ezorm.core.meta.AbstractSchemaMetadata.getObject(AbstractSchemaMetadata.java:111)
        at org.hswebframework.ezorm.rdb.metadata.RDBSchemaMetadata.getObject(RDBSchemaMetadata.java:102)
        at org.hswebframework.ezorm.rdb.metadata.RDBSchemaMetadata.getTable(RDBSchemaMetadata.java:88)
        at org.hswebframework.ezorm.rdb.metadata.RDBSchemaMetadata.getTableOrView(RDBSchemaMetadata.java:110)
        at org.hswebframework.ezorm.core.meta.AbstractDatabaseMetadata.lambda$getObject$1(AbstractDatabaseMetadata.java:66)
        at java.util.Optional.flatMap(Optional.java:241)
        at org.hswebframework.ezorm.core.meta.AbstractDatabaseMetadata.getObject(AbstractDatabaseMetadata.java:66)
        at org.hswebframework.ezorm.rdb.metadata.RDBDatabaseMetadata.getTableOrView(RDBDatabaseMetadata.java:20)
        at org.hswebframework.ezorm.rdb.operator.DefaultDatabaseOperator.query(DefaultDatabaseOperator.java:70)
        at org.hswebframework.ezorm.rdb.mapping.defaults.DefaultReactiveQuery.fetch(DefaultReactiveQuery.java:35)
        at org.iotlinks.network.manager.service.SyncDeviceGatewayState.run(SyncDeviceGatewayState.java:36)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:784)
        ... 13 common frames omitted
Caused by: java.util.NoSuchElementException: Flux#last() didn't observe any onNext signal
        at reactor.core.publisher.MonoTakeLastOne$TakeLastOneSubscriber.onComplete(MonoTakeLastOne.java:102)
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
Assembly trace from producer [reactor.core.publisher.MonoTakeLastOne] :
        reactor.core.publisher.Flux.last
        dev.miku.r2dbc.mysql.LoginFlow$State$2.handle(LoginFlow.java:309)
Error has been observed at the following site(s):
        |_              Flux.last ⇢ at dev.miku.r2dbc.mysql.LoginFlow$State$2.handle(LoginFlow.java:309)
        |_         Flux.doOnError ⇢ at dev.miku.r2dbc.mysql.LoginFlow.login(LoginFlow.java:259)
        |_              Flux.then ⇢ at dev.miku.r2dbc.mysql.LoginFlow.login(LoginFlow.java:260)
        |_                        ⇢ at dev.miku.r2dbc.mysql.MySqlConnectionFactory.lambda$null$0(MySqlConnectionFactory.java:77)
        |_           Mono.flatMap ⇢ at dev.miku.r2dbc.mysql.MySqlConnectionFactory.lambda$from$2(MySqlConnectionFactory.java:77)
        |_           Mono.flatMap ⇢ at dev.miku.r2dbc.mysql.MySqlConnectionFactory.lambda$from$2(MySqlConnectionFactory.java:78)
        |_             Mono.defer ⇢ at dev.miku.r2dbc.mysql.MySqlConnectionFactory.from(MySqlConnectionFactory.java:57)
        |_                        ⇢ at dev.miku.r2dbc.mysql.MySqlConnectionFactory.create(MySqlConnectionFactory.java:46)
        |_              Mono.from ⇢ at io.r2dbc.pool.ConnectionPool.createConnectionPool(ConnectionPool.java:157)
        |_              Mono.from ⇢ at reactor.pool.PoolBuilder.from(PoolBuilder.java:59)
        |_                        ⇢ at reactor.pool.DefaultPoolConfig.allocator(DefaultPoolConfig.java:100)
        |_                        ⇢ at reactor.pool.SimplePool.acquire(SimplePool.java:120)
        |_          Mono.doOnNext ⇢ at io.r2dbc.pool.ConnectionPool.lambda$new$5(ConnectionPool.java:96)
        |_           Mono.flatMap ⇢ at io.r2dbc.pool.ConnectionPool.lambda$new$5(ConnectionPool.java:97)
        |_        Mono.doOnCancel ⇢ at io.r2dbc.pool.ConnectionPool.lambda$new$5(ConnectionPool.java:104)
        |_             Mono.defer ⇢ at io.r2dbc.pool.ConnectionPool.<init>(ConnectionPool.java:91)
        |_             Mono.retry ⇢ at io.r2dbc.pool.ConnectionPool.<init>(ConnectionPool.java:117)
        |_                        ⇢ at io.r2dbc.pool.ConnectionPool.create(ConnectionPool.java:194)
        |_              Mono.from ⇢ at org.springframework.data.r2dbc.connectionfactory.R2dbcTransactionManager.lambda$doBegin$5(R2dbcTransactionManager.java:214)
        |_          Mono.doOnNext ⇢ at org.springframework.data.r2dbc.connectionfactory.R2dbcTransactionManager.lambda$doBegin$5(R2dbcTransactionManager.java:216)
        |_           Mono.flatMap ⇢ at org.springframework.data.r2dbc.connectionfactory.R2dbcTransactionManager.lambda$doBegin$5(R2dbcTransactionManager.java:228)
        |_             Mono.defer ⇢ at org.springframework.data.r2dbc.connectionfactory.R2dbcTransactionManager.doBegin(R2dbcTransactionManager.java:209)
        |_              Mono.then ⇢ at org.springframework.data.r2dbc.connectionfactory.R2dbcTransactionManager.doBegin(R2dbcTransactionManager.java:257)
        |_       Mono.doOnSuccess ⇢ at org.springframework.transaction.reactive.AbstractReactiveTransactionManager.lambda$null$1(AbstractReactiveTransactionManager.java:146)
        |_        Mono.thenReturn ⇢ at org.springframework.transaction.reactive.AbstractReactiveTransactionManager.lambda$null$1(AbstractReactiveTransactionManager.java:147)
        |_             Mono.defer ⇢ at org.springframework.transaction.reactive.AbstractReactiveTransactionManager.lambda$null$3(AbstractReactiveTransactionManager.java:141)
        |_              Mono.then ⇢ at org.springframework.transaction.reactive.AbstractReactiveTransactionManager.lambda$null$2(AbstractReactiveTransactionManager.java:150)
        |_     Mono.onErrorResume ⇢ at org.springframework.transaction.reactive.AbstractReactiveTransactionManager.lambda$null$3(AbstractReactiveTransactionManager.java:148)
        |_           Mono.flatMap ⇢ at org.springframework.transaction.reactive.AbstractReactiveTransactionManager.lambda$null$4(AbstractReactiveTransactionManager.java:137)
        |_           Mono.flatMap ⇢ at org.springframework.transaction.reactive.AbstractReactiveTransactionManager.lambda$getReactiveTransaction$5(AbstractReactiveTransactionManager.java:133)
        |_           Mono.flatMap ⇢ at org.springframework.transaction.reactive.AbstractReactiveTransactionManager.getReactiveTransaction(AbstractReactiveTransactionManager.java:105)
        |_               Mono.map ⇢ at org.springframework.transaction.interceptor.TransactionAspectSupport$ReactiveTransactionSupport.createTransactionIfNecessary(TransactionAspectSupport.java:938)
        |_     Mono.switchIfEmpty ⇢ at org.springframework.transaction.interceptor.TransactionAspectSupport$ReactiveTransactionSupport.createTransactionIfNecessary(TransactionAspectSupport.java:938)
        |_       Mono.flatMapMany ⇢ at org.springframework.transaction.interceptor.TransactionAspectSupport$ReactiveTransactionSupport.lambda$invokeWithinTransaction$9(TransactionAspectSupport.java:894)
        |_       Mono.flatMapMany ⇢ at org.springframework.transaction.interceptor.TransactionAspectSupport$ReactiveTransactionSupport.invokeWithinTransaction(TransactionAspectSupport.java:893)
        |_ Flux.subscriberContext ⇢ at org.springframework.transaction.interceptor.TransactionAspectSupport$ReactiveTransactionSupport.invokeWithinTransaction(TransactionAspectSupport.java:918)
        |_ Flux.subscriberContext ⇢ at org.springframework.transaction.interceptor.TransactionAspectSupport$ReactiveTransactionSupport.invokeWithinTransaction(TransactionAspectSupport.java:919)
        |_       Flux.collectList ⇢ at org.hswebframework.ezorm.rdb.executor.reactive.ReactiveSyncSqlExecutor.select(ReactiveSyncSqlExecutor.java:38)
Stack trace:
                at reactor.core.publisher.MonoTakeLastOne$TakeLastOneSubscriber.onComplete(MonoTakeLastOne.java:102)
                at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onComplete(FluxHandleFuseable.java:223)
                at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onComplete(MonoFlatMapMany.java:252)
                at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onComplete(FluxPeekFuseable.java:270)
                at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onComplete(FluxPeekFuseable.java:270)
                at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onComplete(FluxHandleFuseable.java:223)
                at reactor.core.publisher.FluxConcatArray$ConcatArraySubscriber.onComplete(FluxConcatArray.java:191)
                at reactor.core.publisher.EmitterProcessor.checkTerminated(EmitterProcessor.java:489)
                at reactor.core.publisher.EmitterProcessor.drain(EmitterProcessor.java:350)
                at reactor.core.publisher.EmitterProcessor.onComplete(EmitterProcessor.java:293)
                at reactor.core.publisher.LambdaSubscriber.onComplete(LambdaSubscriber.java:132)
                at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onComplete(FluxPeekFuseable.java:270)
                at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onComplete(FluxHandleFuseable.java:223)
                at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:365)
                at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:368)
                at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:424)
                at reactor.netty.channel.ChannelOperations.onInboundClose(ChannelOperations.java:385)
                at reactor.netty.channel.ChannelOperationsHandler.channelInactive(ChannelOperationsHandler.java:76)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
                at dev.miku.r2dbc.mysql.client.MessageDuplexCodec.channelInactive(MessageDuplexCodec.java:139)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
                at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:389)
                at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
                at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:389)
                at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354)
                at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:1106)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
                at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
                at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
                at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:818)
                at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
                at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
                at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.lang.Thread.run(Thread.java:748)
2024-03-01 13:51:33,245 34946 [main] INFO  o.i.s.c.ExecutorConfiguration$2 - Shutting down ExecutorService 'threadPoolTaskExecutor'
2024-03-01 13:51:33,300 35001 [I/O dispatcher 1] DEBUG o.i.e.s.s.DefaultElasticSearchService - 保存ElasticSearch数据成功,数量:1
```

mysql用自己的客户端连接正常！

**Comment by zhou-hao** [comment]
提供一下连接配置信息

**Comment by wallace1** [comment]
r2dbc:
    url: r2dbc:mysql://iot-host:3306/jetlinks
    username: root
    password: jetlinks
    pool:
      max-size: 32

其中的“iot-host”，会被环境变量替换

**Comment by wallace1** [comment]
在Mysql用Show processlist，发现没有任何jetlinks的连接连上来。

**Comment by zhou-hao** [comment]
`r2dbc:mysql://iot-host:3306/jetlinks?ssl=false&serverZoneId=Asia/Shanghai` 这样试试

**Comment by wallace1** [comment]
zhou-hao，您好！
前两天忙别的事情去了，今天我按您的建议，加上 ssl=false 后，报如下错误：
source [org/hswebframework/web/crud/configuration/EasyOrmConfiguration.class]: Unsatisfied dependency expressed through method 'databaseOperator' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'databaseMetadata' defined in class path resource [org/hswebframework/web/crud/configuration/EasyOrmConfiguration.class]: Unsatisfied dependency expressed through method 'databaseMetadata' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'syncSqlExecutor' defined in class path resource [org/hswebframework/web/crud/configuration/R2dbcSqlExecutorConfiguration.class]: Unsatisfied dependency expressed through method 'syncSqlExecutor' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'reactiveSqlExecutor': Unsatisfied dependency expressed through field 'defaultFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'connectionFactory' defined in class path resource [org/springframework/boot/autoconfigure/r2dbc/ConnectionFactoryConfiguration$ConnectionPoolConnectionFactoryConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.r2dbc.pool.ConnectionPool]: Factory method 'connectionFactory' threw exception; nested exception is java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:797)
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:227)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1358)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:207)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:241)
        at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:723)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:536)
        at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:66)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
        at org.iotlinks.standalone.IoTLinksApplication.main(IoTLinksApplication.java:34)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:597)

你看这是咋回事？
谢谢！

**Comment by zhou-hao** [comment]
看上去是配置文件格式不对

**Comment by wallace1** [comment]
我们把数据库配置写在了启动脚本里，是这样的：

**Comment by wallace1** [comment]
java -Duser.timezone=Asia/Shanghai -Djava.security.egd=file:/dev/./urandom -XX:+UnlockExperimentalVMOptions -Xms26g -Xmx30g -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.rmi.port=4321 -Dcom.sun.management.jmxremote.port=4321 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Djava.rmi.server.hostname=xxxxxxx -XX:+UseCGroupMemoryLimitForHeap -XX:-OmitStackTraceInFastThrow -jar -server app.jar -Dlog4j2.formatMsgNoLookups=true --management.endpoint.health.show-details=ALWAYS --management.endpoints.enabled-by-default=false --management.server.port=-1 --spring.r2dbc.url=r2dbc:mysql://172.17.0.1:3306/keysensing?ssl=FALSE --spring.profiles.active=docker --logging.level.root=INFO --logging.level.org.iotlinks=INFO --logging.level.org.iotlinks.gateway=INFO --logging.level.org.elasticsearch.client=ERROR --device.message.writer.kafka.enabled=false --easyorm.default-schema=keysensing --elasticsearch.index.default-strategy=time-by-month  --spring.redis.password=iotlinks --elasticsearch.client.host=xxxxxxxx --spring.reactor.debug-agent.enabled=false --jetlinks.device.storage.enable-last-data-in-db=false

这有什么问题吗？

**Comment by wallace1** [comment]
zhou-hao，关于SSL=false的问题，好像开发者说，把这个功能disable掉了。请参考：
https://github.com/pgjdbc/r2dbc-postgresql/pull/460

**Comment by zhou-hao** [comment]
https://github.com/asyncer-io/r2dbc-mysql/wiki/Configuration-Options 看看这个？

**Comment by wallace1** [comment]
亲爱的zhou-hao，

             设置成“sslMode=DISABLED”，问题解决了，非常感谢您的帮助！
             谢谢！
